# Generated by Django 6.0.4 on 2026-05-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foodspot_tag',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_proccessed',
            field=models.BooleanField(default=False),
        ),
    ]
