# Generated by Django 6.0.4 on 2026-05-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
