# Generated by Django 6.0.4 on 2026-05-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, default='http://125.0.0.00', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='http://125.0.0.00', max_length=2000, null=True),
        ),
    ]
