# Generated by Django 6.0.4 on 2026-05-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_url',
        ),
    ]
