# Generated by Django 6.0.4 on 2026-06-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comments_content_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='processing', max_length=10),
        ),
    ]
