# Generated by Django 6.0.4 on 2026-08-20 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspot', '0002_initial'),
        ('hotel', '0001_initial'),
        ('post', '0004_post_upload_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='post',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='comments',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hotel__isnull', True), ('user__isnull', False)), models.Q(('hotel__isnull', False), ('user__isnull', True)), _connector='OR'), name='comment_author_is_exactly_one_of_user_or_hotel'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hotel__isnull', True), ('user__isnull', False)), models.Q(('hotel__isnull', False), ('user__isnull', True)), _connector='OR'), name='post_author_is_exactly_one_of_user_or_hotel'),
        ),
    ]
