# Generated by Django 6.0.4 on 2026-08-27 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspot', '0002_initial'),
        ('hotel', '0007_hotelreview_unique_user_hotel_review'),
        ('post', '0005_comments_hotel_post_hotel_alter_comments_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='post_author_is_exactly_one_of_user_or_hotel',
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('hotel__isnull', False), _connector='OR'), name='post_has_user_or_hotel'),
        ),
    ]
