# Generated by Django 6.0.4 on 2026-09-02 08:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_post_post_author_is_exactly_one_of_user_or_hotel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('service', 'Service'), ('cleanliness', 'Cleanliness'), ('value', 'Value')], max_length=20)),
                ('score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='ratings',
            name='unique_user_post_rating',
        ),
        migrations.AddField(
            model_name='postrating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='post.post'),
        ),
        migrations.AddField(
            model_name='postrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='post',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='postrating',
            constraint=models.UniqueConstraint(fields=('post', 'category'), name='unique_post_category_rating'),
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
