# Generated by Django 6.0.4 on 2026-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_postrating_remove_ratings_unique_user_post_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrating',
            name='review',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
