# Generated by Django 6.0.4 on 2026-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_postrating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('instant', 'Instant'), ('video', 'Video'), ('photos', 'Photos')], default='instant', max_length=10),
            preserve_default=False,
        ),
    ]
