# Generated by Django 6.0.4 on 2026-09-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('media_url', models.URLField(blank=True, default='http://125.0.0.00', max_length=2000, null=True)),
                ('media_key', models.CharField(max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
                ('thumbnail_url', models.URLField(blank=True, default='http://125.0.0.00', max_length=2000, null=True)),
                ('category', models.CharField(choices=[('instant', 'Instant'), ('video', 'Video'), ('photos', 'Photos')], max_length=10)),
                ('upload_status', models.CharField(choices=[('processing', 'Processing'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='processing', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='post.post')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
