# Generated by Django 6.0.4 on 2026-09-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_remove_post_media_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='food_spot',
        ),
        migrations.RemoveField(
            model_name='post',
            name='foodspot_tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
