# Generated by Django 6.0.4 on 2026-09-05 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_hotel_is_active'),
        ('post', '0013_remove_post_food_spot_remove_post_foodspot_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('instant', 'Instant')], default='regular', max_length=10),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', 'status', 'expires_at'], name='post_type_status_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('post_type', 'regular'), _negated=True), ('expires_at__isnull', True), _connector='OR'), name='regular_post_has_no_expiry'),
        ),
    ]
