# Generated by Django 6.0.4 on 2026-09-05 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_archived_at_post_expires_at_post_post_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrating',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
