# Generated by Django 6.0.4 on 2026-09-07 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0015_alter_postrating_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=16)),
                ('cover_url', models.URLField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.archive')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_items', to='post.post')),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='archive',
            name='posts',
            field=models.ManyToManyField(related_name='archives', through='accounts.ArchiveItem', to='post.post'),
        ),
        migrations.AddConstraint(
            model_name='archiveitem',
            constraint=models.UniqueConstraint(fields=('archive', 'post'), name='uniq_archive_post'),
        ),
    ]
