# Generated by Django 6.0.4 on 2026-05-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotp',
            name='otp',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='devotp',
            name='phonenumber',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='phonenumber',
            field=models.CharField(),
        ),
    ]
