# Generated by Django 6.0.4 on 2026-09-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_googleidentity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevOTP',
        ),
        migrations.DeleteModel(
            name='OTPrequest',
        ),
        migrations.DeleteModel(
            name='UserAuthentication',
        ),
    ]
