# Generated by Django 6.0.4 on 2026-08-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
