# Generated by Django 6.0.4 on 2026-08-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_fooditem_fooditemvariant_menu_menucategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HotelProfile',
        ),
    ]
