# Generated by Django 6.0.4 on 2026-08-26 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotelreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hotelreview',
            constraint=models.UniqueConstraint(fields=('user', 'hotel'), name='unique_user_hotel_review'),
        ),
    ]
