# Generated by Django 6.0.4 on 2026-08-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_hotelreview_unique_user_hotel_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
