# Generated by Django 6.0.4 on 2026-09-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_backfill_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
