# Generated by Django 6.0.4 on 2026-09-05 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_hotel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrating',
            name='rating_count',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
